# Generated by Django 5.0.4 on 2024-05-22 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SkinBurnDegreeResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="skin_burn_degree/")),
                ("detection", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Skin Burn Degree Result",
                "verbose_name_plural": "Skin Burn Degree Results",
            },
        ),
        migrations.CreateModel(
            name="SkinDiseaseResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="skin_Disease/")),
                ("detection", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Skin Disease Result",
                "verbose_name_plural": "Skin Disease Results",
            },
        ),
        migrations.CreateModel(
            name="SkinRecognitionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="skin_recognition/")),
                ("detection", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Skin Recognition Result",
                "verbose_name_plural": "Skin Recognition Results",
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("birthday", models.DateField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="patient_images/"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
            },
        ),
    ]
