# Generated by Django 5.0.4 on 2024-05-22 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("skincare", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="skinburndegreeresult",
            name="patient",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_skin_burns",
                to="skincare.patient",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="skindiseaseresult",
            name="patient",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_skin_diseases",
                to="skincare.patient",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="skinrecognitionresult",
            name="patient",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_skin_recognitions",
                to="skincare.patient",
            ),
            preserve_default=False,
        ),
    ]
