# Generated by Django 5.0.4 on 2024-05-31 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("skincare", "0002_skinburndegreeresult_patient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female")],
                max_length=1,
                null=True,
            ),
        ),
    ]
